# Generated by Django 5.2.17 on 2026-10-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finsovet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', '-updated_at'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='block',
            name='color',
            field=models.CharField(default='#8e8e93', help_text='HEX, например #1b8a4c', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
