# Generated by Django 5.1.15 on 2026-09-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='client',
            name='what_has',
            field=models.TextField(blank=True, verbose_name='Что есть'),
        ),
        migrations.AlterField(
            model_name='client',
            name='looking_for',
            field=models.TextField(blank=True, verbose_name='Что ищет'),
        ),
    ]
