# Generated by Django 5.1.15 on 2026-09-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_client_first_name_client_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Воронка',
                'verbose_name_plural': 'Воронки',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='lost_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина проигрыша'),
        ),
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(choices=[('unknown', 'Не указан'), ('bitrix', 'База Bitrix'), ('manual', 'Вручную'), ('excel', 'Импорт Excel'), ('whatsapp', 'WhatsApp'), ('call', 'Звонок'), ('instagram', 'Instagram'), ('referral', 'Рекомендация'), ('site', 'Сайт'), ('other', 'Другое')], default='unknown', max_length=16, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='client',
            name='funnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.funnel', verbose_name='Воронка'),
        ),
    ]
