# Generated by Django 5.1.15 on 2026-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_funnel_client_lost_reason_alter_client_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней коммуникации'),
        ),
    ]
