# Generated by Django 5.2.17 on 2026-09-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_backfill_phone_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_finsovet',
            field=models.BooleanField(default=False, verbose_name='Доступ к Финсовету'),
        ),
    ]
