# Generated by Django 5.2.17 on 2026-10-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_user_can_access_finsovet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_finsovet_responsible',
            field=models.BooleanField(default=False, verbose_name='Ответственный в Финсовете'),
        ),
    ]
